ALTER TABLE creature_classlevelstats ADD COLUMN basehp4 MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 1 AFTER basehp3;
ALTER TABLE creature_classlevelstats ADD COLUMN damage_exp4 FLOAT NOT NULL DEFAULT 0 AFTER damage_exp3;

-- MoP
-- basemana UnitClass Paladin
UPDATE `creature_classlevelstats` SET `basemana` = 8726 WHERE `level` = 84 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana`=  8908 WHERE `level` = 85 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana`=  9094 WHERE `level` = 86 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana`=  9310 WHERE `level` = 87 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana`=  9470 WHERE `level` = 88 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana`=  9692 WHERE `level` = 89 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana`=  9916 WHERE `level` = 90 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 9916 WHERE `level` = 90 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 10084 WHERE `level` = 91 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 10312 WHERE `level` = 92 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 10514 WHERE `level` = 93 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 10748 WHERE `level` = 94 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 10954 WHERE `level` = 95 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 11164 WHERE `level` = 96 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 11404 WHERE `level` = 97 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 11618 WHERE `level` = 98 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 11864 WHERE `level` = 99 AND `class` = 2;
UPDATE `creature_classlevelstats` SET `basemana` = 12082 WHERE `level` = 100 AND `class` = 2;


-- basemana UnitClass Mage
UPDATE `creature_classlevelstats` SET `basemana` = 18656 WHERE `level` = 83 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 19024 WHERE `level` = 84 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 19394 WHERE `level` = 85 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 19738 WHERE `level` = 86 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 20114 WHERE `level` = 87 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 20464 WHERE `level` = 88 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 20846 WHERE `level` = 89 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 21262 WHERE `level` = 90 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 21620 WHERE `level` = 91 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 22012 WHERE `level` = 92 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 22406 WHERE `level` = 93 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 22804 WHERE `level` = 94 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 23204 WHERE `level` = 95 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 23578 WHERE `level` = 96 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 24014 WHERE `level` = 97 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 24394 WHERE `level` = 98 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 24836 WHERE `level` = 99 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basemana` = 25282 WHERE `level` = 100 AND `class` = 8;

-- BaseArmor UnitClass Warrior/Paladin/Rogue
UPDATE `creature_classlevelstats` SET `basearmor`= 67 WHERE `level` = 1 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 71 WHERE `level` = 2 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 75 WHERE `level` = 3 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 80 WHERE `level` = 4 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 84 WHERE `level` = 5 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 88 WHERE `level` = 6 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 92 WHERE `level` = 7 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 97 WHERE `level` = 8 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 101 WHERE `level` = 9 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 105 WHERE `level` = 10 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 109 WHERE `level` = 11 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 114 WHERE `level` = 12 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 118 WHERE `level` = 13 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 122 WHERE `level` = 14 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 126 WHERE `level` = 15 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 131 WHERE `level` = 16 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 135 WHERE `level` = 17 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 139 WHERE `level` = 18 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 143 WHERE `level` = 19 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 148 WHERE `level` = 20 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 152 WHERE `level` = 21 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 156 WHERE `level` = 22 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 160 WHERE `level` = 23 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 165 WHERE `level` = 24 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 169 WHERE `level` = 25 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 173 WHERE `level` = 26 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 177 WHERE `level` = 27 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 182 WHERE `level` = 28 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 186 WHERE `level` = 29 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 190 WHERE `level` = 30 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 194 WHERE `level` = 31 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 199 WHERE `level` = 32 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 203 WHERE `level` = 33 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 207 WHERE `level` = 34 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 211 WHERE `level` = 35 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 216 WHERE `level` = 36 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 220 WHERE `level` = 37 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 224 WHERE `level` = 38 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 228 WHERE `level` = 39 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 233 WHERE `level` = 40 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 237 WHERE `level` = 41 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 241 WHERE `level` = 42 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 245 WHERE `level` = 43 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 250 WHERE `level` = 44 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 254 WHERE `level` = 45 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 258 WHERE `level` = 46 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 262 WHERE `level` = 47 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 267 WHERE `level` = 48 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 271 WHERE `level` = 49 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 275 WHERE `level` = 50 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 279 WHERE `level` = 51 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 284 WHERE `level` = 52 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 288 WHERE `level` = 53 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 292 WHERE `level` = 54 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 296 WHERE `level` = 55 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 301 WHERE `level` = 56 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 305 WHERE `level` = 57 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 309 WHERE `level` = 58 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 313 WHERE `level` = 59 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 318 WHERE `level` = 60 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 322 WHERE `level` = 61 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 326 WHERE `level` = 62 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 330 WHERE `level` = 63 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 335 WHERE `level` = 64 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 339 WHERE `level` = 65 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 343 WHERE `level` = 66 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 347 WHERE `level` = 67 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 352 WHERE `level` = 68 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 356 WHERE `level` = 69 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 360 WHERE `level` = 70 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 365 WHERE `level` = 71 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 369 WHERE `level` = 72 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 373 WHERE `level` = 73 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 377 WHERE `level` = 74 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 382 WHERE `level` = 75 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 386 WHERE `level` = 76 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 390 WHERE `level` = 77 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 394 WHERE `level` = 78 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 399 WHERE `level` = 79 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 403 WHERE `level` = 80 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 407 WHERE `level` = 81 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 411 WHERE `level` = 82 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 416 WHERE `level` = 83 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 420 WHERE `level` = 84 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 424 WHERE `level` = 85 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 428 WHERE `level` = 86 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 433 WHERE `level` = 87 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 437 WHERE `level` = 88 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 441 WHERE `level` = 89 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 445 WHERE `level` = 90 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 504 WHERE `level` = 91 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 571 WHERE `level` = 92 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 646 WHERE `level` = 93 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 731 WHERE `level` = 94 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 827 WHERE `level` = 95 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 936 WHERE `level` = 96 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1059 WHERE `level` = 97 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1199 WHERE `level` = 98 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1357 WHERE `level` = 99 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1536 WHERE `level` = 100 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1670 WHERE `level` = 101 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1804 WHERE `level` = 102 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basearmor`= 1938 WHERE `level` = 103 AND `class` IN (1, 2, 4);
-- BaseArmor UnitClass Mage
UPDATE `creature_classlevelstats` SET `basearmor` = 53 WHERE `level` = 1 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 57 WHERE `level` = 2 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 60 WHERE `level` = 3 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 64 WHERE `level` = 4 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 67 WHERE `level` = 5 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 70 WHERE `level` = 6 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 74 WHERE `level` = 7 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 77 WHERE `level` = 8 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 81 WHERE `level` = 9 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 84 WHERE `level` = 10 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 87 WHERE `level` = 11 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 91 WHERE `level` = 12 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 94 WHERE `level` = 13 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 98 WHERE `level` = 14 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 101 WHERE `level` = 15 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 104 WHERE `level` = 16 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 108 WHERE `level` = 17 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 111 WHERE `level` = 18 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 115 WHERE `level` = 19 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 118 WHERE `level` = 20 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 121 WHERE `level` = 21 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 125 WHERE `level` = 22 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 128 WHERE `level` = 23 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 132 WHERE `level` = 24 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 135 WHERE `level` = 25 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 139 WHERE `level` = 26 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 142 WHERE `level` = 27 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 145 WHERE `level` = 28 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 149 WHERE `level` = 29 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 152 WHERE `level` = 30 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 156 WHERE `level` = 31 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 159 WHERE `level` = 32 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 162 WHERE `level` = 33 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 166 WHERE `level` = 34 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 169 WHERE `level` = 35 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 173 WHERE `level` = 36 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 176 WHERE `level` = 37 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 179 WHERE `level` = 38 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 183 WHERE `level` = 39 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 186 WHERE `level` = 40 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 190 WHERE `level` = 41 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 193 WHERE `level` = 42 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 196 WHERE `level` = 43 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 200 WHERE `level` = 44 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 203 WHERE `level` = 45 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 207 WHERE `level` = 46 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 210 WHERE `level` = 47 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 213 WHERE `level` = 48 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 217 WHERE `level` = 49 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 220 WHERE `level` = 50 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 224 WHERE `level` = 51 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 227 WHERE `level` = 52 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 230 WHERE `level` = 53 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 234 WHERE `level` = 54 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 237 WHERE `level` = 55 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 241 WHERE `level` = 56 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 244 WHERE `level` = 57 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 247 WHERE `level` = 58 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 251 WHERE `level` = 59 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 254 WHERE `level` = 60 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 258 WHERE `level` = 61 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 261 WHERE `level` = 62 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 264 WHERE `level` = 63 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 268 WHERE `level` = 64 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 271 WHERE `level` = 65 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 275 WHERE `level` = 66 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 278 WHERE `level` = 67 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 281 WHERE `level` = 68 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 285 WHERE `level` = 69 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 288 WHERE `level` = 70 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 292 WHERE `level` = 71 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 295 WHERE `level` = 72 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 298 WHERE `level` = 73 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 302 WHERE `level` = 74 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 305 WHERE `level` = 75 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 309 WHERE `level` = 76 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 312 WHERE `level` = 77 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 315 WHERE `level` = 78 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 319 WHERE `level` = 79 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 322 WHERE `level` = 80 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 326 WHERE `level` = 81 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 329 WHERE `level` = 82 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 332 WHERE `level` = 83 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 336 WHERE `level` = 84 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 339 WHERE `level` = 85 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 343 WHERE `level` = 86 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 346 WHERE `level` = 87 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 350 WHERE `level` = 88 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 353 WHERE `level` = 89 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 356 WHERE `level` = 90 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 403 WHERE `level` = 91 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 457 WHERE `level` = 92 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 517 WHERE `level` = 93 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 585 WHERE `level` = 94 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 662 WHERE `level` = 95 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 749 WHERE `level` = 96 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 847 WHERE `level` = 97 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 959 WHERE `level` = 98 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 1086 WHERE `level` = 99 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basearmor` = 1229 WHERE `level` = 100 AND `class` = 8;


UPDATE `creature_classlevelstats` SET `basehp3` = 30951 WHERE `level` = 80 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 37187 WHERE `level` = 81 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 44679 WHERE `level` = 82 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 53681 WHERE `level` = 83 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 64496 WHERE `level` = 84 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 77490 WHERE `level` = 85 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 80195 WHERE `level` = 86 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 82994 WHERE `level` = 87 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 85892 WHERE `level` = 88 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 77490 WHERE `level` = 89 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 80195 WHERE `level` = 90 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 82994 WHERE `level` = 91 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 85892 WHERE `level` = 92 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 77490 WHERE `level` = 93 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 80195 WHERE `level` = 94 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 82994 WHERE `level` = 95 AND `class` IN (1, 2, 4);
UPDATE `creature_classlevelstats` SET `basehp3` = 85892 WHERE `level` = 96 AND `class` IN (1, 2, 4);


UPDATE `creature_classlevelstats` SET `basehp3` = 24761 WHERE `level` = 80 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 29750 WHERE `level` = 81 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 35743 WHERE `level` = 82 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 42945 WHERE `level` = 83 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 51597, `basemana` = 9517 WHERE `level` = 84 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 73299, `basemana` = 9694 WHERE `level` = 85 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 86077, `basemana` = 9873 WHERE `level` = 86 AND `class` = 8;
UPDATE `creature_classlevelstats` SET `basehp3` = 107596, `basemana` = 10052 WHERE `level` BETWEEN 87 AND 100 AND `class` = 8;


UPDATE `creature_classlevelstats` SET `damage_exp3`=197.377 WHERE `level`=80 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=197.377 WHERE `level`=81 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=197.377 WHERE `level`=82 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=197.377 WHERE `level`=83 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=197.377 WHERE `level`=84 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=197.377 WHERE `level`=85 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=86 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=87 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=88 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=89 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=90 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=91 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=92 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=93 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=94 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=95 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=96 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=97 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=98 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=99 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=217.475 WHERE `level`=100 AND `class`=1;
UPDATE `creature_classlevelstats` SET `damage_exp3`=195.237 WHERE `level`=80 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=195.237 WHERE `level`=81 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=195.237 WHERE `level`=82 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=195.237 WHERE `level`=83 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=195.237 WHERE `level`=84 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=195.237 WHERE `level`=85 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=86 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=87 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=88 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=89 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=90 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=91 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=92 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=93 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=94 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=95 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=96 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=97 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=98 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=99 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=215.339 WHERE `level`=100 AND `class`=2;
UPDATE `creature_classlevelstats` SET `damage_exp3`=191.179 WHERE `level`=80 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=191.179 WHERE `level`=81 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=191.179 WHERE `level`=82 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=191.179 WHERE `level`=83 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=191.179 WHERE `level`=84 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=191.179 WHERE `level`=85 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=86 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=87 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=88 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=89 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=90 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=91 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=92 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=93 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=94 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=95 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=96 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=97 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=98 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=99 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=211.376 WHERE `level`=100 AND `class`=4;
UPDATE `creature_classlevelstats` SET `damage_exp3`=183.236 WHERE `level`=80 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=183.236 WHERE `level`=81 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=183.236 WHERE `level`=82 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=183.236 WHERE `level`=83 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=183.236 WHERE `level`=84 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=183.236 WHERE `level`=85 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=86 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=87 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=88 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=89 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=90 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=91 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=92 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=93 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=94 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=95 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=96 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=97 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=98 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=99 AND `class`=8;
UPDATE `creature_classlevelstats` SET `damage_exp3`=203.275 WHERE `level`=100 AND `class`=8;

UPDATE creature_classlevelstats SET basehp4=83 WHERE class=1 AND level=1;
UPDATE creature_classlevelstats SET basehp4=114 WHERE class=1 AND level=2;
UPDATE creature_classlevelstats SET basehp4=141 WHERE class=1 AND level=3;
UPDATE creature_classlevelstats SET basehp4=163 WHERE class=1 AND level=4;
UPDATE creature_classlevelstats SET basehp4=200 WHERE class=1 AND level=5;
UPDATE creature_classlevelstats SET basehp4=236 WHERE class=1 AND level=6;
UPDATE creature_classlevelstats SET basehp4=248 WHERE class=1 AND level=7;
UPDATE creature_classlevelstats SET basehp4=285 WHERE class=1 AND level=8;
UPDATE creature_classlevelstats SET basehp4=321 WHERE class=1 AND level=9;
UPDATE creature_classlevelstats SET basehp4=334 WHERE class=1 AND level=10;
UPDATE creature_classlevelstats SET basehp4=370 WHERE class=1 AND level=11;
UPDATE creature_classlevelstats SET basehp4=407 WHERE class=1 AND level=12;
UPDATE creature_classlevelstats SET basehp4=419 WHERE class=1 AND level=13;
UPDATE creature_classlevelstats SET basehp4=455 WHERE class=1 AND level=14;
UPDATE creature_classlevelstats SET basehp4=492 WHERE class=1 AND level=15;
UPDATE creature_classlevelstats SET basehp4=504 WHERE class=1 AND level=16;
UPDATE creature_classlevelstats SET basehp4=541 WHERE class=1 AND level=17;
UPDATE creature_classlevelstats SET basehp4=577 WHERE class=1 AND level=18;
UPDATE creature_classlevelstats SET basehp4=589 WHERE class=1 AND level=19;
UPDATE creature_classlevelstats SET basehp4=626 WHERE class=1 AND level=20;
UPDATE creature_classlevelstats SET basehp4=662 WHERE class=1 AND level=21;
UPDATE creature_classlevelstats SET basehp4=674 WHERE class=1 AND level=22;
UPDATE creature_classlevelstats SET basehp4=711 WHERE class=1 AND level=23;
UPDATE creature_classlevelstats SET basehp4=738 WHERE class=1 AND level=24;
UPDATE creature_classlevelstats SET basehp4=774 WHERE class=1 AND level=25;
UPDATE creature_classlevelstats SET basehp4=818 WHERE class=1 AND level=26;
UPDATE creature_classlevelstats SET basehp4=879 WHERE class=1 AND level=27;
UPDATE creature_classlevelstats SET basehp4=923 WHERE class=1 AND level=28;
UPDATE creature_classlevelstats SET basehp4=969 WHERE class=1 AND level=29;
UPDATE creature_classlevelstats SET basehp4=1042 WHERE class=1 AND level=30;
UPDATE creature_classlevelstats SET basehp4=1098 WHERE class=1 AND level=31;
UPDATE creature_classlevelstats SET basehp4=1157 WHERE class=1 AND level=32;
UPDATE creature_classlevelstats SET basehp4=1218 WHERE class=1 AND level=33;
UPDATE creature_classlevelstats SET basehp4=1281 WHERE class=1 AND level=34;
UPDATE creature_classlevelstats SET basehp4=1347 WHERE class=1 AND level=35;
UPDATE creature_classlevelstats SET basehp4=1415 WHERE class=1 AND level=36;
UPDATE creature_classlevelstats SET basehp4=1485 WHERE class=1 AND level=37;
UPDATE creature_classlevelstats SET basehp4=1558 WHERE class=1 AND level=38;
UPDATE creature_classlevelstats SET basehp4=1634 WHERE class=1 AND level=39;
UPDATE creature_classlevelstats SET basehp4=1712 WHERE class=1 AND level=40;
UPDATE creature_classlevelstats SET basehp4=1792 WHERE class=1 AND level=41;
UPDATE creature_classlevelstats SET basehp4=1875 WHERE class=1 AND level=42;
UPDATE creature_classlevelstats SET basehp4=1960 WHERE class=1 AND level=43;
UPDATE creature_classlevelstats SET basehp4=2048 WHERE class=1 AND level=44;
UPDATE creature_classlevelstats SET basehp4=2138 WHERE class=1 AND level=45;
UPDATE creature_classlevelstats SET basehp4=2230 WHERE class=1 AND level=46;
UPDATE creature_classlevelstats SET basehp4=2325 WHERE class=1 AND level=47;
UPDATE creature_classlevelstats SET basehp4=2423 WHERE class=1 AND level=48;
UPDATE creature_classlevelstats SET basehp4=2506 WHERE class=1 AND level=49;
UPDATE creature_classlevelstats SET basehp4=2627 WHERE class=1 AND level=50;
UPDATE creature_classlevelstats SET basehp4=2754 WHERE class=1 AND level=51;
UPDATE creature_classlevelstats SET basehp4=2885 WHERE class=1 AND level=52;
UPDATE creature_classlevelstats SET basehp4=3022 WHERE class=1 AND level=53;
UPDATE creature_classlevelstats SET basehp4=3163 WHERE class=1 AND level=54;
UPDATE creature_classlevelstats SET basehp4=3309 WHERE class=1 AND level=55;
UPDATE creature_classlevelstats SET basehp4=3460 WHERE class=1 AND level=56;
UPDATE creature_classlevelstats SET basehp4=3616 WHERE class=1 AND level=57;
UPDATE creature_classlevelstats SET basehp4=3680 WHERE class=1 AND level=58;
UPDATE creature_classlevelstats SET basehp4=3743 WHERE class=1 AND level=59;
UPDATE creature_classlevelstats SET basehp4=3807 WHERE class=1 AND level=60;
UPDATE creature_classlevelstats SET basehp4=3871 WHERE class=1 AND level=61;
UPDATE creature_classlevelstats SET basehp4=3934 WHERE class=1 AND level=62;
UPDATE creature_classlevelstats SET basehp4=3998 WHERE class=1 AND level=63;
UPDATE creature_classlevelstats SET basehp4=4062 WHERE class=1 AND level=64;
UPDATE creature_classlevelstats SET basehp4=4126 WHERE class=1 AND level=65;
UPDATE creature_classlevelstats SET basehp4=4189 WHERE class=1 AND level=66;
UPDATE creature_classlevelstats SET basehp4=4253 WHERE class=1 AND level=67;
UPDATE creature_classlevelstats SET basehp4=4317 WHERE class=1 AND level=68;
UPDATE creature_classlevelstats SET basehp4=4380 WHERE class=1 AND level=69;
UPDATE creature_classlevelstats SET basehp4=4444 WHERE class=1 AND level=70;
UPDATE creature_classlevelstats SET basehp4=4720 WHERE class=1 AND level=71;
UPDATE creature_classlevelstats SET basehp4=5013 WHERE class=1 AND level=72;
UPDATE creature_classlevelstats SET basehp4=5325 WHERE class=1 AND level=73;
UPDATE creature_classlevelstats SET basehp4=5656 WHERE class=1 AND level=74;
UPDATE creature_classlevelstats SET basehp4=6008 WHERE class=1 AND level=75;
UPDATE creature_classlevelstats SET basehp4=6381 WHERE class=1 AND level=76;
UPDATE creature_classlevelstats SET basehp4=6778 WHERE class=1 AND level=77;
UPDATE creature_classlevelstats SET basehp4=7199 WHERE class=1 AND level=78;
UPDATE creature_classlevelstats SET basehp4=7646 WHERE class=1 AND level=79;
UPDATE creature_classlevelstats SET basehp4=8121 WHERE class=1 AND level=80;
UPDATE creature_classlevelstats SET basehp4=11349 WHERE class=1 AND level=81;
UPDATE creature_classlevelstats SET basehp4=15860 WHERE class=1 AND level=82;
UPDATE creature_classlevelstats SET basehp4=22164 WHERE class=1 AND level=83;
UPDATE creature_classlevelstats SET basehp4=30974 WHERE class=1 AND level=84;
UPDATE creature_classlevelstats SET basehp4=43285 WHERE class=1 AND level=85;
UPDATE creature_classlevelstats SET basehp4=55250 WHERE class=1 AND level=86;
UPDATE creature_classlevelstats SET basehp4=70523 WHERE class=1 AND level=87;
UPDATE creature_classlevelstats SET basehp4=90017 WHERE class=1 AND level=88;
UPDATE creature_classlevelstats SET basehp4=114901 WHERE class=1 AND level=89;
UPDATE creature_classlevelstats SET basehp4=146663 WHERE class=1 AND level=90;
UPDATE creature_classlevelstats SET basehp4=187204 WHERE class=1 AND level=91;
UPDATE creature_classlevelstats SET basehp4=238953 WHERE class=1 AND level=92;
UPDATE creature_classlevelstats SET basehp4=305006 WHERE class=1 AND level=93;
UPDATE creature_classlevelstats SET basehp4=389318 WHERE class=1 AND level=94;
UPDATE creature_classlevelstats SET basehp4=496937 WHERE class=1 AND level=95;
UPDATE creature_classlevelstats SET basehp4=634304 WHERE class=1 AND level=96;
UPDATE creature_classlevelstats SET basehp4=809644 WHERE class=1 AND level=97;
UPDATE creature_classlevelstats SET basehp4=1033452 WHERE class=1 AND level=98;
UPDATE creature_classlevelstats SET basehp4=1319127 WHERE class=1 AND level=99;
UPDATE creature_classlevelstats SET basehp4=1683771 WHERE class=1 AND level=100;
-- CLASS_TYPE PALADIN
UPDATE creature_classlevelstats SET basehp4=83 WHERE class=2 AND level=1;
UPDATE creature_classlevelstats SET basehp4=114 WHERE class=2 AND level=2;
UPDATE creature_classlevelstats SET basehp4=141 WHERE class=2 AND level=3;
UPDATE creature_classlevelstats SET basehp4=163 WHERE class=2 AND level=4;
UPDATE creature_classlevelstats SET basehp4=200 WHERE class=2 AND level=5;
UPDATE creature_classlevelstats SET basehp4=236 WHERE class=2 AND level=6;
UPDATE creature_classlevelstats SET basehp4=248 WHERE class=2 AND level=7;
UPDATE creature_classlevelstats SET basehp4=285 WHERE class=2 AND level=8;
UPDATE creature_classlevelstats SET basehp4=321 WHERE class=2 AND level=9;
UPDATE creature_classlevelstats SET basehp4=334 WHERE class=2 AND level=10;
UPDATE creature_classlevelstats SET basehp4=370 WHERE class=2 AND level=11;
UPDATE creature_classlevelstats SET basehp4=407 WHERE class=2 AND level=12;
UPDATE creature_classlevelstats SET basehp4=419 WHERE class=2 AND level=13;
UPDATE creature_classlevelstats SET basehp4=455 WHERE class=2 AND level=14;
UPDATE creature_classlevelstats SET basehp4=492 WHERE class=2 AND level=15;
UPDATE creature_classlevelstats SET basehp4=504 WHERE class=2 AND level=16;
UPDATE creature_classlevelstats SET basehp4=541 WHERE class=2 AND level=17;
UPDATE creature_classlevelstats SET basehp4=577 WHERE class=2 AND level=18;
UPDATE creature_classlevelstats SET basehp4=589 WHERE class=2 AND level=19;
UPDATE creature_classlevelstats SET basehp4=626 WHERE class=2 AND level=20;
UPDATE creature_classlevelstats SET basehp4=662 WHERE class=2 AND level=21;
UPDATE creature_classlevelstats SET basehp4=674 WHERE class=2 AND level=22;
UPDATE creature_classlevelstats SET basehp4=711 WHERE class=2 AND level=23;
UPDATE creature_classlevelstats SET basehp4=738 WHERE class=2 AND level=24;
UPDATE creature_classlevelstats SET basehp4=774 WHERE class=2 AND level=25;
UPDATE creature_classlevelstats SET basehp4=818 WHERE class=2 AND level=26;
UPDATE creature_classlevelstats SET basehp4=879 WHERE class=2 AND level=27;
UPDATE creature_classlevelstats SET basehp4=923 WHERE class=2 AND level=28;
UPDATE creature_classlevelstats SET basehp4=969 WHERE class=2 AND level=29;
UPDATE creature_classlevelstats SET basehp4=1042 WHERE class=2 AND level=30;
UPDATE creature_classlevelstats SET basehp4=1098 WHERE class=2 AND level=31;
UPDATE creature_classlevelstats SET basehp4=1157 WHERE class=2 AND level=32;
UPDATE creature_classlevelstats SET basehp4=1218 WHERE class=2 AND level=33;
UPDATE creature_classlevelstats SET basehp4=1281 WHERE class=2 AND level=34;
UPDATE creature_classlevelstats SET basehp4=1347 WHERE class=2 AND level=35;
UPDATE creature_classlevelstats SET basehp4=1415 WHERE class=2 AND level=36;
UPDATE creature_classlevelstats SET basehp4=1485 WHERE class=2 AND level=37;
UPDATE creature_classlevelstats SET basehp4=1558 WHERE class=2 AND level=38;
UPDATE creature_classlevelstats SET basehp4=1634 WHERE class=2 AND level=39;
UPDATE creature_classlevelstats SET basehp4=1712 WHERE class=2 AND level=40;
UPDATE creature_classlevelstats SET basehp4=1792 WHERE class=2 AND level=41;
UPDATE creature_classlevelstats SET basehp4=1875 WHERE class=2 AND level=42;
UPDATE creature_classlevelstats SET basehp4=1960 WHERE class=2 AND level=43;
UPDATE creature_classlevelstats SET basehp4=2048 WHERE class=2 AND level=44;
UPDATE creature_classlevelstats SET basehp4=2138 WHERE class=2 AND level=45;
UPDATE creature_classlevelstats SET basehp4=2230 WHERE class=2 AND level=46;
UPDATE creature_classlevelstats SET basehp4=2325 WHERE class=2 AND level=47;
UPDATE creature_classlevelstats SET basehp4=2423 WHERE class=2 AND level=48;
UPDATE creature_classlevelstats SET basehp4=2506 WHERE class=2 AND level=49;
UPDATE creature_classlevelstats SET basehp4=2627 WHERE class=2 AND level=50;
UPDATE creature_classlevelstats SET basehp4=2754 WHERE class=2 AND level=51;
UPDATE creature_classlevelstats SET basehp4=2885 WHERE class=2 AND level=52;
UPDATE creature_classlevelstats SET basehp4=3022 WHERE class=2 AND level=53;
UPDATE creature_classlevelstats SET basehp4=3163 WHERE class=2 AND level=54;
UPDATE creature_classlevelstats SET basehp4=3309 WHERE class=2 AND level=55;
UPDATE creature_classlevelstats SET basehp4=3460 WHERE class=2 AND level=56;
UPDATE creature_classlevelstats SET basehp4=3616 WHERE class=2 AND level=57;
UPDATE creature_classlevelstats SET basehp4=3680 WHERE class=2 AND level=58;
UPDATE creature_classlevelstats SET basehp4=3743 WHERE class=2 AND level=59;
UPDATE creature_classlevelstats SET basehp4=3807 WHERE class=2 AND level=60;
UPDATE creature_classlevelstats SET basehp4=3871 WHERE class=2 AND level=61;
UPDATE creature_classlevelstats SET basehp4=3934 WHERE class=2 AND level=62;
UPDATE creature_classlevelstats SET basehp4=3998 WHERE class=2 AND level=63;
UPDATE creature_classlevelstats SET basehp4=4062 WHERE class=2 AND level=64;
UPDATE creature_classlevelstats SET basehp4=4126 WHERE class=2 AND level=65;
UPDATE creature_classlevelstats SET basehp4=4189 WHERE class=2 AND level=66;
UPDATE creature_classlevelstats SET basehp4=4253 WHERE class=2 AND level=67;
UPDATE creature_classlevelstats SET basehp4=4317 WHERE class=2 AND level=68;
UPDATE creature_classlevelstats SET basehp4=4380 WHERE class=2 AND level=69;
UPDATE creature_classlevelstats SET basehp4=4444 WHERE class=2 AND level=70;
UPDATE creature_classlevelstats SET basehp4=4720 WHERE class=2 AND level=71;
UPDATE creature_classlevelstats SET basehp4=5013 WHERE class=2 AND level=72;
UPDATE creature_classlevelstats SET basehp4=5325 WHERE class=2 AND level=73;
UPDATE creature_classlevelstats SET basehp4=5656 WHERE class=2 AND level=74;
UPDATE creature_classlevelstats SET basehp4=6008 WHERE class=2 AND level=75;
UPDATE creature_classlevelstats SET basehp4=6381 WHERE class=2 AND level=76;
UPDATE creature_classlevelstats SET basehp4=6778 WHERE class=2 AND level=77;
UPDATE creature_classlevelstats SET basehp4=7199 WHERE class=2 AND level=78;
UPDATE creature_classlevelstats SET basehp4=7646 WHERE class=2 AND level=79;
UPDATE creature_classlevelstats SET basehp4=8121 WHERE class=2 AND level=80;
UPDATE creature_classlevelstats SET basehp4=11349 WHERE class=2 AND level=81;
UPDATE creature_classlevelstats SET basehp4=15860 WHERE class=2 AND level=82;
UPDATE creature_classlevelstats SET basehp4=22164 WHERE class=2 AND level=83;
UPDATE creature_classlevelstats SET basehp4=30974 WHERE class=2 AND level=84;
UPDATE creature_classlevelstats SET basehp4=43285 WHERE class=2 AND level=85;
UPDATE creature_classlevelstats SET basehp4=55250 WHERE class=2 AND level=86;
UPDATE creature_classlevelstats SET basehp4=70523 WHERE class=2 AND level=87;
UPDATE creature_classlevelstats SET basehp4=90017 WHERE class=2 AND level=88;
UPDATE creature_classlevelstats SET basehp4=114901 WHERE class=2 AND level=89;
UPDATE creature_classlevelstats SET basehp4=146663 WHERE class=2 AND level=90;
UPDATE creature_classlevelstats SET basehp4=187204 WHERE class=2 AND level=91;
UPDATE creature_classlevelstats SET basehp4=238953 WHERE class=2 AND level=92;
UPDATE creature_classlevelstats SET basehp4=305006 WHERE class=2 AND level=93;
UPDATE creature_classlevelstats SET basehp4=389318 WHERE class=2 AND level=94;
UPDATE creature_classlevelstats SET basehp4=496937 WHERE class=2 AND level=95;
UPDATE creature_classlevelstats SET basehp4=634304 WHERE class=2 AND level=96;
UPDATE creature_classlevelstats SET basehp4=809644 WHERE class=2 AND level=97;
UPDATE creature_classlevelstats SET basehp4=1033452 WHERE class=2 AND level=98;
UPDATE creature_classlevelstats SET basehp4=1319127 WHERE class=2 AND level=99;
UPDATE creature_classlevelstats SET basehp4=1683771 WHERE class=2 AND level=100;
-- CLASS_TYPE ROGUE
UPDATE creature_classlevelstats SET basehp4=83 WHERE class=4 AND level=1;
UPDATE creature_classlevelstats SET basehp4=114 WHERE class=4 AND level=2;
UPDATE creature_classlevelstats SET basehp4=141 WHERE class=4 AND level=3;
UPDATE creature_classlevelstats SET basehp4=163 WHERE class=4 AND level=4;
UPDATE creature_classlevelstats SET basehp4=200 WHERE class=4 AND level=5;
UPDATE creature_classlevelstats SET basehp4=236 WHERE class=4 AND level=6;
UPDATE creature_classlevelstats SET basehp4=248 WHERE class=4 AND level=7;
UPDATE creature_classlevelstats SET basehp4=285 WHERE class=4 AND level=8;
UPDATE creature_classlevelstats SET basehp4=321 WHERE class=4 AND level=9;
UPDATE creature_classlevelstats SET basehp4=334 WHERE class=4 AND level=10;
UPDATE creature_classlevelstats SET basehp4=370 WHERE class=4 AND level=11;
UPDATE creature_classlevelstats SET basehp4=407 WHERE class=4 AND level=12;
UPDATE creature_classlevelstats SET basehp4=419 WHERE class=4 AND level=13;
UPDATE creature_classlevelstats SET basehp4=455 WHERE class=4 AND level=14;
UPDATE creature_classlevelstats SET basehp4=492 WHERE class=4 AND level=15;
UPDATE creature_classlevelstats SET basehp4=504 WHERE class=4 AND level=16;
UPDATE creature_classlevelstats SET basehp4=541 WHERE class=4 AND level=17;
UPDATE creature_classlevelstats SET basehp4=577 WHERE class=4 AND level=18;
UPDATE creature_classlevelstats SET basehp4=589 WHERE class=4 AND level=19;
UPDATE creature_classlevelstats SET basehp4=626 WHERE class=4 AND level=20;
UPDATE creature_classlevelstats SET basehp4=662 WHERE class=4 AND level=21;
UPDATE creature_classlevelstats SET basehp4=674 WHERE class=4 AND level=22;
UPDATE creature_classlevelstats SET basehp4=711 WHERE class=4 AND level=23;
UPDATE creature_classlevelstats SET basehp4=738 WHERE class=4 AND level=24;
UPDATE creature_classlevelstats SET basehp4=774 WHERE class=4 AND level=25;
UPDATE creature_classlevelstats SET basehp4=818 WHERE class=4 AND level=26;
UPDATE creature_classlevelstats SET basehp4=879 WHERE class=4 AND level=27;
UPDATE creature_classlevelstats SET basehp4=923 WHERE class=4 AND level=28;
UPDATE creature_classlevelstats SET basehp4=969 WHERE class=4 AND level=29;
UPDATE creature_classlevelstats SET basehp4=1042 WHERE class=4 AND level=30;
UPDATE creature_classlevelstats SET basehp4=1098 WHERE class=4 AND level=31;
UPDATE creature_classlevelstats SET basehp4=1157 WHERE class=4 AND level=32;
UPDATE creature_classlevelstats SET basehp4=1218 WHERE class=4 AND level=33;
UPDATE creature_classlevelstats SET basehp4=1281 WHERE class=4 AND level=34;
UPDATE creature_classlevelstats SET basehp4=1347 WHERE class=4 AND level=35;
UPDATE creature_classlevelstats SET basehp4=1415 WHERE class=4 AND level=36;
UPDATE creature_classlevelstats SET basehp4=1485 WHERE class=4 AND level=37;
UPDATE creature_classlevelstats SET basehp4=1558 WHERE class=4 AND level=38;
UPDATE creature_classlevelstats SET basehp4=1634 WHERE class=4 AND level=39;
UPDATE creature_classlevelstats SET basehp4=1712 WHERE class=4 AND level=40;
UPDATE creature_classlevelstats SET basehp4=1792 WHERE class=4 AND level=41;
UPDATE creature_classlevelstats SET basehp4=1875 WHERE class=4 AND level=42;
UPDATE creature_classlevelstats SET basehp4=1960 WHERE class=4 AND level=43;
UPDATE creature_classlevelstats SET basehp4=2048 WHERE class=4 AND level=44;
UPDATE creature_classlevelstats SET basehp4=2138 WHERE class=4 AND level=45;
UPDATE creature_classlevelstats SET basehp4=2230 WHERE class=4 AND level=46;
UPDATE creature_classlevelstats SET basehp4=2325 WHERE class=4 AND level=47;
UPDATE creature_classlevelstats SET basehp4=2423 WHERE class=4 AND level=48;
UPDATE creature_classlevelstats SET basehp4=2506 WHERE class=4 AND level=49;
UPDATE creature_classlevelstats SET basehp4=2627 WHERE class=4 AND level=50;
UPDATE creature_classlevelstats SET basehp4=2754 WHERE class=4 AND level=51;
UPDATE creature_classlevelstats SET basehp4=2885 WHERE class=4 AND level=52;
UPDATE creature_classlevelstats SET basehp4=3022 WHERE class=4 AND level=53;
UPDATE creature_classlevelstats SET basehp4=3163 WHERE class=4 AND level=54;
UPDATE creature_classlevelstats SET basehp4=3309 WHERE class=4 AND level=55;
UPDATE creature_classlevelstats SET basehp4=3460 WHERE class=4 AND level=56;
UPDATE creature_classlevelstats SET basehp4=3616 WHERE class=4 AND level=57;
UPDATE creature_classlevelstats SET basehp4=3680 WHERE class=4 AND level=58;
UPDATE creature_classlevelstats SET basehp4=3743 WHERE class=4 AND level=59;
UPDATE creature_classlevelstats SET basehp4=3807 WHERE class=4 AND level=60;
UPDATE creature_classlevelstats SET basehp4=3871 WHERE class=4 AND level=61;
UPDATE creature_classlevelstats SET basehp4=3934 WHERE class=4 AND level=62;
UPDATE creature_classlevelstats SET basehp4=3998 WHERE class=4 AND level=63;
UPDATE creature_classlevelstats SET basehp4=4062 WHERE class=4 AND level=64;
UPDATE creature_classlevelstats SET basehp4=4126 WHERE class=4 AND level=65;
UPDATE creature_classlevelstats SET basehp4=4189 WHERE class=4 AND level=66;
UPDATE creature_classlevelstats SET basehp4=4253 WHERE class=4 AND level=67;
UPDATE creature_classlevelstats SET basehp4=4317 WHERE class=4 AND level=68;
UPDATE creature_classlevelstats SET basehp4=4380 WHERE class=4 AND level=69;
UPDATE creature_classlevelstats SET basehp4=4444 WHERE class=4 AND level=70;
UPDATE creature_classlevelstats SET basehp4=4720 WHERE class=4 AND level=71;
UPDATE creature_classlevelstats SET basehp4=5013 WHERE class=4 AND level=72;
UPDATE creature_classlevelstats SET basehp4=5325 WHERE class=4 AND level=73;
UPDATE creature_classlevelstats SET basehp4=5656 WHERE class=4 AND level=74;
UPDATE creature_classlevelstats SET basehp4=6008 WHERE class=4 AND level=75;
UPDATE creature_classlevelstats SET basehp4=6381 WHERE class=4 AND level=76;
UPDATE creature_classlevelstats SET basehp4=6778 WHERE class=4 AND level=77;
UPDATE creature_classlevelstats SET basehp4=7199 WHERE class=4 AND level=78;
UPDATE creature_classlevelstats SET basehp4=7646 WHERE class=4 AND level=79;
UPDATE creature_classlevelstats SET basehp4=8121 WHERE class=4 AND level=80;
UPDATE creature_classlevelstats SET basehp4=11349 WHERE class=4 AND level=81;
UPDATE creature_classlevelstats SET basehp4=15860 WHERE class=4 AND level=82;
UPDATE creature_classlevelstats SET basehp4=22164 WHERE class=4 AND level=83;
UPDATE creature_classlevelstats SET basehp4=30974 WHERE class=4 AND level=84;
UPDATE creature_classlevelstats SET basehp4=43285 WHERE class=4 AND level=85;
UPDATE creature_classlevelstats SET basehp4=55250 WHERE class=4 AND level=86;
UPDATE creature_classlevelstats SET basehp4=70523 WHERE class=4 AND level=87;
UPDATE creature_classlevelstats SET basehp4=90017 WHERE class=4 AND level=88;
UPDATE creature_classlevelstats SET basehp4=114901 WHERE class=4 AND level=89;
UPDATE creature_classlevelstats SET basehp4=146663 WHERE class=4 AND level=90;
UPDATE creature_classlevelstats SET basehp4=187204 WHERE class=4 AND level=91;
UPDATE creature_classlevelstats SET basehp4=238953 WHERE class=4 AND level=92;
UPDATE creature_classlevelstats SET basehp4=305006 WHERE class=4 AND level=93;
UPDATE creature_classlevelstats SET basehp4=389318 WHERE class=4 AND level=94;
UPDATE creature_classlevelstats SET basehp4=496937 WHERE class=4 AND level=95;
UPDATE creature_classlevelstats SET basehp4=634304 WHERE class=4 AND level=96;
UPDATE creature_classlevelstats SET basehp4=809644 WHERE class=4 AND level=97;
UPDATE creature_classlevelstats SET basehp4=1033452 WHERE class=4 AND level=98;
UPDATE creature_classlevelstats SET basehp4=1319127 WHERE class=4 AND level=99;
UPDATE creature_classlevelstats SET basehp4=1683771 WHERE class=4 AND level=100;
-- CLASS_TYPE MAGE
UPDATE creature_classlevelstats SET basehp4=83 WHERE class=8 AND level=1;
UPDATE creature_classlevelstats SET basehp4=114 WHERE class=8 AND level=2;
UPDATE creature_classlevelstats SET basehp4=141 WHERE class=8 AND level=3;
UPDATE creature_classlevelstats SET basehp4=163 WHERE class=8 AND level=4;
UPDATE creature_classlevelstats SET basehp4=200 WHERE class=8 AND level=5;
UPDATE creature_classlevelstats SET basehp4=236 WHERE class=8 AND level=6;
UPDATE creature_classlevelstats SET basehp4=248 WHERE class=8 AND level=7;
UPDATE creature_classlevelstats SET basehp4=285 WHERE class=8 AND level=8;
UPDATE creature_classlevelstats SET basehp4=321 WHERE class=8 AND level=9;
UPDATE creature_classlevelstats SET basehp4=334 WHERE class=8 AND level=10;
UPDATE creature_classlevelstats SET basehp4=370 WHERE class=8 AND level=11;
UPDATE creature_classlevelstats SET basehp4=407 WHERE class=8 AND level=12;
UPDATE creature_classlevelstats SET basehp4=419 WHERE class=8 AND level=13;
UPDATE creature_classlevelstats SET basehp4=455 WHERE class=8 AND level=14;
UPDATE creature_classlevelstats SET basehp4=492 WHERE class=8 AND level=15;
UPDATE creature_classlevelstats SET basehp4=504 WHERE class=8 AND level=16;
UPDATE creature_classlevelstats SET basehp4=541 WHERE class=8 AND level=17;
UPDATE creature_classlevelstats SET basehp4=577 WHERE class=8 AND level=18;
UPDATE creature_classlevelstats SET basehp4=589 WHERE class=8 AND level=19;
UPDATE creature_classlevelstats SET basehp4=626 WHERE class=8 AND level=20;
UPDATE creature_classlevelstats SET basehp4=662 WHERE class=8 AND level=21;
UPDATE creature_classlevelstats SET basehp4=674 WHERE class=8 AND level=22;
UPDATE creature_classlevelstats SET basehp4=711 WHERE class=8 AND level=23;
UPDATE creature_classlevelstats SET basehp4=738 WHERE class=8 AND level=24;
UPDATE creature_classlevelstats SET basehp4=774 WHERE class=8 AND level=25;
UPDATE creature_classlevelstats SET basehp4=818 WHERE class=8 AND level=26;
UPDATE creature_classlevelstats SET basehp4=879 WHERE class=8 AND level=27;
UPDATE creature_classlevelstats SET basehp4=923 WHERE class=8 AND level=28;
UPDATE creature_classlevelstats SET basehp4=969 WHERE class=8 AND level=29;
UPDATE creature_classlevelstats SET basehp4=1042 WHERE class=8 AND level=30;
UPDATE creature_classlevelstats SET basehp4=1098 WHERE class=8 AND level=31;
UPDATE creature_classlevelstats SET basehp4=1157 WHERE class=8 AND level=32;
UPDATE creature_classlevelstats SET basehp4=1218 WHERE class=8 AND level=33;
UPDATE creature_classlevelstats SET basehp4=1281 WHERE class=8 AND level=34;
UPDATE creature_classlevelstats SET basehp4=1347 WHERE class=8 AND level=35;
UPDATE creature_classlevelstats SET basehp4=1415 WHERE class=8 AND level=36;
UPDATE creature_classlevelstats SET basehp4=1485 WHERE class=8 AND level=37;
UPDATE creature_classlevelstats SET basehp4=1558 WHERE class=8 AND level=38;
UPDATE creature_classlevelstats SET basehp4=1634 WHERE class=8 AND level=39;
UPDATE creature_classlevelstats SET basehp4=1712 WHERE class=8 AND level=40;
UPDATE creature_classlevelstats SET basehp4=1792 WHERE class=8 AND level=41;
UPDATE creature_classlevelstats SET basehp4=1875 WHERE class=8 AND level=42;
UPDATE creature_classlevelstats SET basehp4=1960 WHERE class=8 AND level=43;
UPDATE creature_classlevelstats SET basehp4=2048 WHERE class=8 AND level=44;
UPDATE creature_classlevelstats SET basehp4=2138 WHERE class=8 AND level=45;
UPDATE creature_classlevelstats SET basehp4=2230 WHERE class=8 AND level=46;
UPDATE creature_classlevelstats SET basehp4=2325 WHERE class=8 AND level=47;
UPDATE creature_classlevelstats SET basehp4=2423 WHERE class=8 AND level=48;
UPDATE creature_classlevelstats SET basehp4=2506 WHERE class=8 AND level=49;
UPDATE creature_classlevelstats SET basehp4=2627 WHERE class=8 AND level=50;
UPDATE creature_classlevelstats SET basehp4=2754 WHERE class=8 AND level=51;
UPDATE creature_classlevelstats SET basehp4=2885 WHERE class=8 AND level=52;
UPDATE creature_classlevelstats SET basehp4=3022 WHERE class=8 AND level=53;
UPDATE creature_classlevelstats SET basehp4=3163 WHERE class=8 AND level=54;
UPDATE creature_classlevelstats SET basehp4=3309 WHERE class=8 AND level=55;
UPDATE creature_classlevelstats SET basehp4=3460 WHERE class=8 AND level=56;
UPDATE creature_classlevelstats SET basehp4=3616 WHERE class=8 AND level=57;
UPDATE creature_classlevelstats SET basehp4=3680 WHERE class=8 AND level=58;
UPDATE creature_classlevelstats SET basehp4=3743 WHERE class=8 AND level=59;
UPDATE creature_classlevelstats SET basehp4=3807 WHERE class=8 AND level=60;
UPDATE creature_classlevelstats SET basehp4=3871 WHERE class=8 AND level=61;
UPDATE creature_classlevelstats SET basehp4=3934 WHERE class=8 AND level=62;
UPDATE creature_classlevelstats SET basehp4=3998 WHERE class=8 AND level=63;
UPDATE creature_classlevelstats SET basehp4=4062 WHERE class=8 AND level=64;
UPDATE creature_classlevelstats SET basehp4=4126 WHERE class=8 AND level=65;
UPDATE creature_classlevelstats SET basehp4=4189 WHERE class=8 AND level=66;
UPDATE creature_classlevelstats SET basehp4=4253 WHERE class=8 AND level=67;
UPDATE creature_classlevelstats SET basehp4=4317 WHERE class=8 AND level=68;
UPDATE creature_classlevelstats SET basehp4=4380 WHERE class=8 AND level=69;
UPDATE creature_classlevelstats SET basehp4=4444 WHERE class=8 AND level=70;
UPDATE creature_classlevelstats SET basehp4=4720 WHERE class=8 AND level=71;
UPDATE creature_classlevelstats SET basehp4=5013 WHERE class=8 AND level=72;
UPDATE creature_classlevelstats SET basehp4=5325 WHERE class=8 AND level=73;
UPDATE creature_classlevelstats SET basehp4=5656 WHERE class=8 AND level=74;
UPDATE creature_classlevelstats SET basehp4=6008 WHERE class=8 AND level=75;
UPDATE creature_classlevelstats SET basehp4=6381 WHERE class=8 AND level=76;
UPDATE creature_classlevelstats SET basehp4=6778 WHERE class=8 AND level=77;
UPDATE creature_classlevelstats SET basehp4=7199 WHERE class=8 AND level=78;
UPDATE creature_classlevelstats SET basehp4=7646 WHERE class=8 AND level=79;
UPDATE creature_classlevelstats SET basehp4=8121 WHERE class=8 AND level=80;
UPDATE creature_classlevelstats SET basehp4=11349 WHERE class=8 AND level=81;
UPDATE creature_classlevelstats SET basehp4=15860 WHERE class=8 AND level=82;
UPDATE creature_classlevelstats SET basehp4=22164 WHERE class=8 AND level=83;
UPDATE creature_classlevelstats SET basehp4=30974 WHERE class=8 AND level=84;
UPDATE creature_classlevelstats SET basehp4=43285 WHERE class=8 AND level=85;
UPDATE creature_classlevelstats SET basehp4=55250 WHERE class=8 AND level=86;
UPDATE creature_classlevelstats SET basehp4=70523 WHERE class=8 AND level=87;
UPDATE creature_classlevelstats SET basehp4=90017 WHERE class=8 AND level=88;
UPDATE creature_classlevelstats SET basehp4=114901 WHERE class=8 AND level=89;
UPDATE creature_classlevelstats SET basehp4=146663 WHERE class=8 AND level=90;
UPDATE creature_classlevelstats SET basehp4=187204 WHERE class=8 AND level=91;
UPDATE creature_classlevelstats SET basehp4=238953 WHERE class=8 AND level=92;
UPDATE creature_classlevelstats SET basehp4=305006 WHERE class=8 AND level=93;
UPDATE creature_classlevelstats SET basehp4=389318 WHERE class=8 AND level=94;
UPDATE creature_classlevelstats SET basehp4=496937 WHERE class=8 AND level=95;
UPDATE creature_classlevelstats SET basehp4=634304 WHERE class=8 AND level=96;
UPDATE creature_classlevelstats SET basehp4=809644 WHERE class=8 AND level=97;
UPDATE creature_classlevelstats SET basehp4=1033452 WHERE class=8 AND level=98;
UPDATE creature_classlevelstats SET basehp4=1319127 WHERE class=8 AND level=99;



UPDATE creature_classlevelstats SET basehp4=1683771, damage_exp4= , basearmor= ,basemana= WHERE class=8 AND level=100;


INSERT INTO `creature_classlevelstats` (`level`, `class`, `OldContentBaseHP`, `CurrentContentBaseHP`, `basemana`, `basearmor`) VALUES

